configure: judge build dir permission
If this patch is applied, issue:

https://gitlab.com/qemu-project/qemu/-/issues/321

can be closed.

Signed-off-by: Guo Zhi <qtxuning1999@sjtu.edu.cn>
Message-Id: <20220405134819.3644952-1-qtxuning1999@sjtu.edu.cn>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,7 +24,13 @@ then
     then
         if test -f $MARKER
         then
-           rm -rf build
+            if test -w $MARKER
+            then
+                rm -rf build
+            else
+                echo "ERROR: ./build dir already exists and can not be removed due to permission"
+                exit 1
+            fi
         else
             echo "ERROR: ./build dir already exists and was not previously created by configure"
             exit 1
